### ISSUE TITLE
训练完doupo以后, 运行inference的时候显示: ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by lk1983823** [GaoPeng97/transformer-xl-chinese#14]
输入命令: bash scripts/doupo_base_gpu.sh inference, 现实错误.
Run inference...
INFO:tensorflow:n_token 84827
building vocab with min_freq=0, max_size=None
final vocab size 4786 from 4786 unique tokens
WARNING:tensorflow:From /home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lk_TC/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /media/lukuan/s/DL_lk/NLP/transformer-xl-chinese/tf/model.py:616: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /media/lukuan/s/DL_lk/NLP/transformer-xl-chinese/tf/model.py:705: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:#params: 43046566
2019-08-26 08:58:24.718474: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-26 08:58:24.821696: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-26 08:58:24.822190: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55bcb0b0ca80 executing computations on platform CUDA. Devices:
2019-08-26 08:58:24.822203: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-08-26 08:58:24.823656: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 4008359999 Hz
2019-08-26 08:58:24.824027: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55bcb0b76b90 executing computations on platform Host. Devices:
2019-08-26 08:58:24.824052: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-26 08:58:24.824230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8225
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 6.62GiB
2019-08-26 08:58:24.824245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-08-26 08:58:24.824957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-26 08:58:24.824975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-08-26 08:58:24.824979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-08-26 08:58:24.825117: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6442 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
lk_print_show:  None
Traceback (most recent call last):
  File "train_gpu.py", line 735, in <module>
    tf.app.run()
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lk_TC/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_gpu.py", line 499, in main
    inference(n_token, cutoffs, "/gpu:0")
  File "train_gpu.py", line 578, in inference
    saver.restore(sess, eval_ckpt_path)
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lk_TC/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
谢谢!

**Comment by lk1983823** [comment]
在doupo_base_gpu.sh的文件中:
训练时, 模型保存地址的参数设置是:
--model_dir=EXP-doupo4-1_head-1e4
但是inference的模型读取地址是: 
--model_dir=EXP-doupo4/lr1e4_new
这导致了在inference的时候, tf.train.latest_checkpoint(FLAGS.model_dir) 输出none.
从而,
```
Traceback (most recent call last):
  File "train_gpu.py", line 738, in <module>
    tf.app.run()
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lk_TC/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_gpu.py", line 500, in main
    inference(n_token, cutoffs, "/gpu:0")
  File "train_gpu.py", line 581, in inference
    saver.restore(sess, eval_ckpt_path)
  File "/home/lukuan/.pyenv/versions/anaconda3-5.0.1/envs/lk_TC/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
```
这是怎么回事? 是我哪里搞错了么? 还是作者的参数设置有问题?

**Comment by AaronZhangL** [comment]
@lk1983823 我也遇到了相同的问题，请问如何解决的呢？
