### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by Seumi** [GaoPeng97/transformer-xl-chinese#3]
i get this error when i run train_gpu.py
my env:
ubuntu16.04 with Tesla P100 (cuda9.0,cudnn7.6)
tf 1.12
numpy 1.16.4
python 3.6

does anything wrong？

====================
INFO:tensorflow:n_token 10091
INFO:tensorflow:[train] File names ['train.bsz-128.tlen-100.tfrecords']
INFO:tensorflow:num of batches 612
WARNING:tensorflow:From ~\tf_gpu\lib\site-packages\tensorflow\python\ops\sparse_ops.py:1165: sparse_to_dense (from tensorflow.python.ops.spa
rse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "train_gpu.py", line 735, in <module>
    tf.app.run()
  File "~\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_gpu.py", line 495, in main
    train(n_token, cutoffs, "/gpu:0")
  File "train_gpu.py", line 280, in train
    mems=mems_i)
  File "train_gpu.py", line 229, in single_core_graph
    is_training=is_training)
  File "train_gpu.py", line 197, in model_fn
    proj_same_dim=FLAGS.proj_same_dim)
  File "~\tf\model.py", line 554, in transformer
    proj_same_dim=proj_same_dim)
  File "~\tf\model.py", line 258, in mask_adaptive_logsoftmax
    output = _logit(hidden, params_W, softmax_b, params_projs)
  File "~\tf\model.py", line 243, in _logit
    y = tf.einsum('ibd,ed->ibe', y, proj)
  File "~\tf_gpu\lib\site-packages\tensorflow\python\ops\special_math_ops.py", line 257, in einsum
    axes_to_sum)
  File "~\tf_gpu\lib\site-packages\tensorflow\python\ops\special_math_ops.py", line 306, in _einsum_reduction
    if len(t1_axis_labels) != len(t1.get_shape()):
AttributeError: 'list' object has no attribute 'get_shape'
================

**Comment by Seumi** [comment]
This error occurred in 'tangshi' dataset, but work fine in 'poetry' ddataset

**Comment by GaoPeng97** [comment]
I am so sorry that I have not met this error before . Did you try other datasets like doupo, test?  Did they work fine ?
